-- MySQL Script generated by MySQL Workbench
-- пн, 27-сер-2018 19:48:46 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`recipe_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recipe_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recipe_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(45) NULL,
  `date_created` DATETIME NULL,
  `date_updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recipes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `steps` TEXT NOT NULL,
  `cooktime` DATETIME NULL,
  `recipe_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_recipes_recipe_info_idx` (`recipe_info_id` ASC),
  CONSTRAINT `fk_recipes_recipe_info`
    FOREIGN KEY (`recipe_info_id`)
    REFERENCES `mydb`.`recipe_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuisine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cuisine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cuisine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuisine_title` VARCHAR(75) NULL,
  `cuisine_location` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_title` VARCHAR(100) NULL,
  `category_type` TINYINT(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredient_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredient_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredient_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article` LONGTEXT NULL,
  `carbs` INT NULL,
  `fats` INT NULL,
  `proteine` INT NULL,
  `salt` INT NULL,
  `alergy_status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingredien_title` VARCHAR(120) NOT NULL,
  `ingredient_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `ingredien_title_UNIQUE` (`ingredien_title` ASC),
  INDEX `fk_ingredients_ingredient_info1_idx` (`ingredient_info_id` ASC),
  CONSTRAINT `fk_ingredients_ingredient_info1`
    FOREIGN KEY (`ingredient_info_id`)
    REFERENCES `mydb`.`ingredient_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipes_has_cuisine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recipes_has_cuisine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recipes_has_cuisine` (
  `recipes_id` INT NOT NULL,
  `cuisine_id` INT NOT NULL,
  PRIMARY KEY (`recipes_id`, `cuisine_id`),
  INDEX `fk_recipes_has_cuisine_cuisine1_idx` (`cuisine_id` ASC),
  INDEX `fk_recipes_has_cuisine_recipes1_idx` (`recipes_id` ASC),
  CONSTRAINT `fk_recipes_has_cuisine_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `mydb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_has_cuisine_cuisine1`
    FOREIGN KEY (`cuisine_id`)
    REFERENCES `mydb`.`cuisine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipes_has_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recipes_has_ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recipes_has_ingredients` (
  `recipes_id` INT NOT NULL,
  `ingredients_id` INT NOT NULL,
  PRIMARY KEY (`recipes_id`, `ingredients_id`),
  INDEX `fk_recipes_has_ingredients_ingredients1_idx` (`ingredients_id` ASC),
  INDEX `fk_recipes_has_ingredients_recipes1_idx` (`recipes_id` ASC),
  CONSTRAINT `fk_recipes_has_ingredients_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `mydb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `mydb`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipes_has_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recipes_has_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recipes_has_category` (
  `recipes_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`recipes_id`, `category_id`),
  INDEX `fk_recipes_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_recipes_has_category_recipes1_idx` (`recipes_id` ASC),
  CONSTRAINT `fk_recipes_has_category_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `mydb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
